Feature/choose hotel
ptrkc/drivent-back pull request #10
Opened 2021-09-15 12:42 UTC by luanerdy

2021-09-15 16:14 UTC, ptrkc commented on src/routers/client/index.ts
> +router.use("/hotel", hotelRouter);
Eu achava que todas as rotas precisavam do tokenValidationMiddleware, pra ver se o usuário ta logado. @thiagoribb tira essa dúvida, por favor.

2021-09-15 16:14 UTC, ptrkc approved these changes

2021-09-15 18:19 UTC, thiagoribb requested changes

2021-09-15 18:19 UTC, thiagoribb commented on src/routers/client/index.ts
> +router.use("/hotel", hotelRouter);
Sim, Patrick. Muito bem observado.

2021-09-16 17:26 UTC, ptrkc approved these changes

2021-09-16 17:27 UTC, thiagoribb approved these changes

2021-09-16 17:27 UTC, merged