Feature/finalize payment
ptrkc/drivent-back pull request #5
Opened 2021-09-05 19:18 UTC by luanerdy

2021-09-06 16:11 UTC, ptrkc approved these changes
Show

2021-09-06 22:23 UTC, thiagoribb requested changes

2021-09-06 22:23 UTC, thiagoribb commented on src/controllers/client/booking.ts
> +}
Se essas interfaces estão sendo exportadas para serem reutilizadas em outros arquivos, é recomendado que eles sejam definidos na pasta de `interfaces`.

2021-09-08 16:58 UTC, thiagoribb approved these changes

2021-09-08 23:50 UTC, merged