Feature payment validation
ptrkc/drivent-back pull request #6
Opened 2021-09-07 01:51 UTC by PauloMoss

2021-09-08 18:51 UTC, thiagoribb requested changes
Não é possível aprovar implementações de novas rotas sem a cobertura de testes de integração.

2021-09-08 18:51 UTC, thiagoribb commented on src/controllers/client/booking.ts
>  }
Se essa interface for utilizada em outros arquivos, é recomendado que ela fique na pasta de `interfaces`.

2021-09-08 21:50 UTC, thiagoribb approved these changes

2021-09-09 22:57 UTC, thiagoribb approved these changes

2021-09-10 05:59 UTC, luanerdy approved these changes

2021-09-10 05:59 UTC, merged